### ISSUE TITLE
Lookup table reference error

### ISSUE THREAD

**Issue by ymylei** [PaloAltoNetworks/Splunk-Apps#123]
After installing 6.0.0, I'm getting an error when the lookup table 'minemeldfeeds_lookup' is being referenced in the props.conf definition for pan:threat and pan:traffic. 

I'm unable to figure out where this lookup table is supposed to be generated, as it's not one of the ones being generated from savedsearches.conf nor is there a "default" table included with the TA.

**Comment by sutcocuk** [comment]
> I'm definitely still seeing this issue in a fresh install of 6.2.0 on a brand new Splunk deployment.
> 
> The savedsearch and KV lookups enabled by default are causing errors out of the box.
> 
> We're going to disable these in the `local` configuration, but it would be nice to not have them on by default.
> 
> ![image](https://user-images.githubusercontent.com/5017324/85164445-5f960e80-b232-11ea-8f3f-738e50a13098.png)

Hi hosom, I have the same problem. Where can i disable it, in which .conf exactly. Will this cause performance problems?

**Comment by steadfasterX** [comment]
this command finally fixed it for me: https://community.splunk.com/t5/All-Apps-and-Add-ons/Palo-Alto-Networks-for-Splunk-v-6-1-1-Receiving-error-quot/m-p/503637/highlight/true#M62091

**Comment by btorresgil** [comment]
Sorry this took so long to resolve. The workaround shared here by @steadfasterX is the best one for app version 6.x. Sadly, the way Splunk replicates kvstores is problematic for the App, and we apologize for the problems this has caused to customers.

Through a redesign, **this issue is resolved in App/Add-on version 7.0 or higher.**

I will close this issue, but keep it pinned for now so others can find the workaround or know to upgrade to 7.0+.

Thank you everyone.
