### ISSUE TITLE
dest_name field should not contain a port

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/Splunk-Apps#128]
## Describe the bug

`dest_name` field contains a port: `example.com:8000`

## Expected behavior

It should instead be EVAL'd from dest_hostname or url to strip the port number.

## Current behavior

Currently dest_name is aliased from dest_hostname which contains a port (eg. :8000). 

## Context

dest_name is just the hostname according to CIM

## Your Environment

- Version used: 6.2.0
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Splunk 8

**Comment by btorresgil** [comment]
Pull Request proposed: https://github.com/PaloAltoNetworks/Splunk-Apps/pull/129

**Comment by malvidin** [comment]
Because the `dest_port` is provided and extracted elsewhere in the log line, I recommend both `dest_name` exclude the port. If the original GET/POST included a Host header that included the port, a `dest_hostname` that includes the host/port makes sense.

Depending on performance and style, one location for a potential change is the transforms.conf. I assume the trailing `/` in the URL related regular expressions are a style choice, since they do not change the extracted value.
https://github.com/PaloAltoNetworks/Splunk-Apps/blob/b5debbeb69ecf21a3df74e9c3dbf43bfcd7867f2/Splunk_TA_paloalto/default/transforms.conf#L123
```[extract_dest_hostname]
SOURCE_KEY = misc
REGEX = ^(?<dest_hostname>(?<dest_name>[^:/]*)[^/]*)/
````
Other options include the replace in https://github.com/PaloAltoNetworks/Splunk-Apps/commit/dc4eb07659e8e803445d00210390e6a03a2e35a1:
```
EVAL-dest_name                      = replace(dest_hostname, "^([^:/]+).*", "\1")
```
Or the inverse of that:
```
EVAL-dest_name                      = replace(dest_hostname, ":.*", "")
```
Or mvindex/split:
```
EVAL-dest_name                      = mvindex(split(dest_hostname, ":"), 0)
```

I did not find any of the eval statements significantly faster than another, so it likely comes down to style. 

The `misc` field will still include any `dest_name`, `port`, `file`, or `path`, and can be parsed with [URL Toolbox](https://splunkbase.splunk.com/app/2734/).

**Comment by btorresgil** [comment]
Hi @malvidin, thanks for all the details in #127 and here.

It sounds like the PR #129 will satisfy your requirements, then. I completely agree that `dest_name` should not include the port.

I'm going to alias `dest_hostname` to `dest_host` as well, since I think that is the better place for the socket address (domain/port combination) to live.  Based on the common use of the word "host", it seems like `dest_host` should contain the port: https://developer.mozilla.org/en-US/docs/Web/API/URL/host  Though I'm still interested in any Splunk documentation that confirms this.

This is technically a breaking change for some people because `dest_name` field is in-use and will change behavior, but since the change is a bug fix (it should never have had the current behavior) I think its fair to release this in a bug fix release. We'll merge the PR and get it released ASAP.

Thanks for your feedback!
