### ISSUE TITLE
Missing sourcetype settings for pan:log (according to Splunk PS)

### ISSUE THREAD

**Issue by idev** [PaloAltoNetworks/Splunk-Apps#252]
## Describe the bug

We did a review of our Splunk Cloud environment with Splunk Professional Services, and they made some recommendations for our TAs to improve performance. One of the recommendation also is maybe valuable for the Palo TA.

## Expected behavior

The sourcetype [pan:log] should  define also the following settings:
LINE_BREAKER
TIME_FORMAT
EVENT_BREAKER_ENABLE
EVENT_BREAKER

## Current behavior

The sourcetype [pan:log] is missing the settings:
LINE_BREAKER
TIME_FORMAT
EVENT_BREAKER_ENABLE
EVENT_BREAKER

This is just a hint I want to forward.

Hope it helps.

**Comment by btorresgil** [comment]
I'd be interested if Splunk PS would like to explain these recommendations. But I currently don't see a performance advantage to this over the current configuration, and the risk of making these changes is high because it affects all log types.

I will close this for now, but please comment here if there is more details on these recommendations. Thanks!
