### ISSUE TITLE
Version 8.1.0 not listed as Splunk Cloud compatible on Splunkbase

### ISSUE THREAD

**Issue by inspired** [PaloAltoNetworks/Splunk-Apps#314]
## Describe the bug

https://apps.splunk.com/app/2757/ does not list latest version or any version of the add-on as compatible with Splunk Cloud

## Expected behavior

Change it to also be Splunk Cloud compatible / vet the app for Splunk Cloud

## Current behavior

Unable to install in Splunk Cloud

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by paulmnguyen** [comment]
Hey @inspired Thanks for opening the bug. The add-on has been removed from cloud since the Add-on Builder(AOB) requied an update. We are currently working on a new release for Add-On Builder 4.1.3. Currently working through app-inspect. Please be on the lookout for that version.

**Comment by EatMoreChicken** [comment]
For the time being, would it be okay to just remove the `default/addon_builder.conf` and install? I don't think Splunk needs it for anything beyond when using the Add-on Builder correct?

**Comment by paulmnguyen** [comment]
@EatMoreChicken From my understanding you can't install an app into Splunk Cloud that isn't certified. Is that no longer the case?

**Comment by EatMoreChicken** [comment]
@paulmnguyen Yep that is still the case. I tried to remove the `default/addon_builder.conf` since I don't believe you need that for normal operations and tried to get it Cloud vetted, but realized there were other blockers preventing the Cloud vetting related to the `PanHeader` directories that I submitted another issue for yesterday.

For the time being. I ended up making a custom version of the app that is stripped down and just has the search-time configs so the extractions, tagging, etc. can work while the update for the add-on is being worked on.

**Comment by paulmnguyen** [comment]
Please update to 8.1.1 as it is cloud certified
